# Generated by Django 4.1.7 on 2023-08-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='datestart',
            field=models.DateField(verbose_name='Дата начала цели'),
        ),
    ]
